### ISSUE TITLE
Remove ` "dev": true,`  from deps and peerDeps from package-lock.json

### ISSUE THREAD

**Issue by ewianda** [cfaester/enzyme-adapter-react-18#3]
The presence of `"dev": true` for packages like `has`, `props-types` is causing problems for `pnmp`, since hey are not considered as `production` dependencies.

**Comment by cfaester** [comment]
I am not really sure what you mean @ewianda as I am not using pnpm. Surely, you do not want testing utilities in your production builds?

**Comment by cfaester** [comment]
Closed as stale.
