### ISSUE TITLE
How to initialise it in CJS?

### ISSUE THREAD

**Issue by ashleyyy94** [cfaester/enzyme-adapter-react-18#8]
I am trying to configure the Enzyme adapter using the below in my `jest.setup.js`:

`const { configure } = require('enzyme');
const { Adapter } = require('@cfaester/enzyme-adapter-react-18');
configure({ adapter: new Adapter() });`

However, when I run my test files, it is throwing a typerror as below:
![image](https://github.com/cfaester/enzyme-adapter-react-18/assets/20836965/930d5e76-9b07-43ad-8595-a62f95f2a2c3)

Any advice?

Thank you.

**Comment by hjelmeir** [comment]
did you try `const Adapter = require('@cfaester/enzyme-adapter-react-18')`?

**Comment by nasimoyz** [comment]
Looks like `const Adapter = require('@cfaester/enzyme-adapter-react-18');` will give you:
[console log] `Adapter { default: [class ReactEighteenAdapter extends EnzymeAdapter] }`

We can access the `default` property inside that object instead via:
`const Adapter = require('@cfaester/enzyme-adapter-react-18').default;`

**Comment by cfaester** [comment]
Seems resolved.
